server.port: 8082

spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    properties:
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: PLAIN
      request.timeout.ms: 20000
      retry.backoff.ms: 500
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${CLUSTER_API_KEY}" password="${CLUSTER_API_SECRET}";
      security.protocol: SASL_SSL

      schema.registry.url: ${SR_URL}
      basic.auth.credentials.source: USER_INFO
      schema.registry.basic.auth.user.info: ${SR_API_KEY}:${SR_API_SECRET}
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      topics:
        message: message
